server:
  port: 8888
spring:
  application:
    name: spring-boot-admin-server
  profiles:
    active:
      - insecure
            
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

security2:
    user:
      name: "sa"
      password: "sa"